version: '3.3'

services:

  owncloud:
    image: owncloud/server:latest    # 10.13.2-arm64v8
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=tudominio.com  # Nombre dominio v치lido 
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=user      # Usuario admin Owncloud
      - OWNCLOUD_ADMIN_PASSWORD=p4ssw0rd  # Contrase침a admin Owncloud 
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    volumes:
      - ./files:/mnt/data

  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M    # Puedes variar este par치metro
      - MARIADB_INNODB_LOG_FILE_SIZE=64M   # Puedes variar este par치metro
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    volumes:
      - ./redis:/var/lib/redis

volumes:
  files:
  mysql:
  redis:      
